FROM ubuntu:16.04

RUN apt-get update -qq \
 && apt-get upgrade -y \
 && apt-get install -qq -y gettext-base openssh-client wget git make curl cmake php7.0 php7.0-cli php7.0-zip php7.0-fpm php7.0-bcmath php7.0-mbstring php7.0-xml php7.0-pgsql php7.0-curl php-pear libssl-dev libssl-doc \
 && git config --global user.email "nighty@nigthwatch.io" \
 && git config --global user.name "Nightwatch Bot"

